name: Reproducible Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - nix
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix-teleport:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build
        run: nix build .
      - name: Rebuild
        run: nix build --rebuild
      - name: sha256sum output
        run: sha256sum result/bin/teleport
      - name: sha256sum check
        run: |
          echo "4d01693ebb01a830a24b70b70ebfec0b313a49fb9c0acbf091d79a4be89b515a *result/bin/teleport" | sha256sum --strict --chec
      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result
