name: Reproducible Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - nix
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix-teleport:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build
        run: nix build .
      - name: Rebuild
        run: nix build --rebuild
      - name: sha256sum output
        run: sha256sum result/bin/teleport
      - name: sha256sum check
        run: |
          echo "293208b0d4d5a48bff03a43c8b54f1d3b3238e56a236d7d4c2775ad5d3b03274 *result/bin/teleport" | sha256sum --strict --chec
      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result
