name: Reproducible Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - nix
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix-teleport:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build
        run: nix build .
      - name: Rebuild
        run: nix build --rebuild
      - name: sha256sum output
        run: sha256sum result/bin/teleport
      - name: sha256sum check
        run: |
          #echo "81d266299ca6e435f0812259eef0b1a37cd5de716a71f9d2a4bab6db6a35c598 *result/bin/teleport" | sha256sum --strict --chec
      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result

  docker-nix-teleport:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          target: nix-build-output
          push: false
          tags: sbellem/teleport
          outputs: type=local,dest=bin
      - name: sha256sum output
        run: sha256sum bin/teleport
